### ISSUE TITLE
Possible bug when sending too many events

### ISSUE THREAD

**Issue by ybeaufort** [spacebro/spacebro#17]
I have an application that watches file changes in a folder and emits events for every changes with spacebro-client.
I had about 50 000 files in that folder and deleted them all at once. The application began sending the events to the spacebro server.
During the process, I was looking at the spacebro-server interface which was logging the received events as usual, until it completely stopped logging the events and froze.

Not much longer after, the computer froze entirely so I'm not sure if the problem is coming from spacebro or not. I've had those weird freezes before in other situations.

**Comment by hugohil** [comment]
Hi @ybeaufort 
It is indeed an issue that we already had with spacebro.
We added the `--semiverbose` flag to only show the event name (no data) in the logs.
If server is still laggy, you can use the `-M` (`--mute`) flag to simply remove logs from the server.

Also, I advise you to use the `-H` (`--hide`) flag to hide the dashboard and display log in more "stdout" way.

None of them are quite ideal, so if you come up with a clever idea to handle big events flow, let's speak about it here. Closing the issue for now.

**Comment by gabrielstuff** [comment]
Hello here,
I would suggest to let it open and avoid to let issues fall into holes 🕳 

What I had in mind is simply throttle the event log, with few `ms` to fix this.

If we keep this issue close, I suggest to add in the README a section about improvement and recommandation.
