### ISSUE TITLE
Weird bug on port and service name

### ISSUE THREAD

**Issue by Art2B** [spacebro/spacebro#3]
Hi guys,

I'm actually running two spacebro on the same local network, and I have a weird bug. One is called 'spacebro', and the other 'spacechacal'. I've several apps which connects to a service named 'spacebro', and that part is fine. They are running on the same port.

However, when I launch my 'spacechacal' server, All the apps connects to this service too. The only way to make things works is to change the port of 'spacechacal'. 

There must be a bug with the port of spacebro. 

![Mind Blown](http://1.media.dorkly.cvcdn.com/50/27/0d41808f60af8871fa122b3b0f37ab1b.gif)

**Comment by hugohil** [comment]
Spacebro has changed a lot since, closing the issue for now, please open a new one with more details if this bug persists on latest version of spacebro and spacebro-client (might also be client related).
