### ISSUE TITLE
Must be in spacebro/bin folder to call --help option

### ISSUE THREAD

**Issue by MPolymath** [spacebro/spacebro#5]
An error occurs when trying to launch spacebro binary --help option when not inside the binary folder.

Example
Does not work:
/opt/player/sources/spacebro/bin/spacebro --help

Works
spacebro --help

**Comment by hugohil** [comment]
I think you forgot the `.`.

The following work as expected (`-h` and `--help` are the same):
```
$ ./Sources/js/soixante/spacebro/bin/spacebro -h
```
